[package]
name = "schnorrkel"
version = "0.6.1"
authors = ["Jeff Burdges <jeff@web3.foundation>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/w3f/schnorrkel"
documentation = "https://docs.rs/schnorrkel"
keywords = ["cryptography", "ed25519", "curve25519", "signature", "ECC"]
categories = ["cryptography", "no-std"]
description = "Schnorr VRF, signatures, etc. using the Ristretto group"
exclude = [ ".gitignore", "TESTVECTORS", "res/*" ]

# [lib]
# name = "sr"
# path = "src/lib.rs"
# crate-type = ["staticlib"]


# [badges]
# travis-ci = { repository = "dalek-cryptography/ed25519-dalek", branch = "master"}

[dependencies.curve25519-dalek]
# git = "https://github.com/dalek-cryptography/curve25519-dalek"
version = "1.0"
default-features = false

[dependencies.ed25519-dalek]
git = "https://github.com/extropiescom/ed25519-dalek"
branch = "master"
version = "1.0.0-pre.1"
default-features = false

[dependencies.subtle]
version = "2.0.0"
default-features = false

[dependencies.merlin] 
#version = "1.1.0"
git = "https://github.com/extropiescom/merlin"
# features = ["debug-transcript"]
default-features = false

[dependencies.rand]
version = "0.5.0"  # was "0.6.4"
default-features = false
features = ["i128_support"]

[dependencies.rand_chacha]
version = "0.1.0"
default-features = false

[dependencies.serde]
version = "^1.0"
default-features = false
optional = true

[dependencies.sha3]
version = "^0.8"
default-features = false

[dependencies.sha2]
version = "^0.8"
default-features = false

[dependencies.failure]
version = "^0.1.1"
default-features = false

[dependencies.clear_on_drop]
version = "0.2"
default-features = false

[dependencies.alloc-cortex-m]
version = "0.3.5"

[profile.dev]
opt-level = 0 
lto = false

[profile.release]
opt-level = 3
lto = true

# [dev-dependencies]
# hex = "^0.3"
# sha2 = "^0.8"
# bincode = "^0.9"
# criterion = "0.2"

[[bench]]
name = "schnorr_benchmarks"
harness = false

[features]
default = ["std", "u64_backend","soft_rng"]
embedded = ["embedded_ed25519","embedded_curve25519"]
soft_rng = ["std"]
std = ["curve25519-dalek/std", "rand/std"]
alloc = ["curve25519-dalek/alloc"]
nightly = ["curve25519-dalek/nightly", "rand/nightly", "clear_on_drop/nightly"]
asm = ["sha2/asm"]
yolocrypto = ["curve25519-dalek/yolocrypto"]
u64_backend = ["curve25519-dalek/u64_backend", "ed25519-dalek/u64_backend"]
u32_backend = ["curve25519-dalek/u32_backend", "ed25519-dalek/u32_backend"]
avx2_backend = ["curve25519-dalek/avx2_backend", "ed25519-dalek/avx2_backend"]
embedded_ed25519 = ["ed25519-dalek/embedded","ed25519-dalek/u32_backend"]
embedded_curve25519 = ["curve25519-dalek/u32_backend"]
